Downgrade swagger 2.8 to 2.7
Swagger 2.8 generates pages that throw a Javascript error
in old versions of Firefox and MS Edge:

   SyntaxError: invalid arrow-function arguments
   (parentheses around the arrow-function may help)

Change-Id: I53ddeceea3c9c1d1004379a03d423cff1c115c70
Signed-off-by: Lott, Christopher (cl778h) <cl778h@att.com>
(cherry picked from commit 9a5db5f7774b6c0035c8abdacb27594df4900906)